---
name: ci
on:
  - push

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - {'toxenv': 'py38', 'container': 'python:3.8'}
          - {'toxenv': 'py39', 'container': 'python:3.9'}
          - {'toxenv': 'py310', 'container': 'python:3.10'}
          - {'toxenv': 'py311', 'container': 'python:3.11'}
          - {'toxenv': 'py312', 'container': 'python:3.12'}
    container:
      image: ${{ matrix.python.container}}
    steps:
      - uses: actions/checkout@v3
      - run: pip install --upgrade tox
      - run: tox -e ${{ matrix.python.toxenv }}
